bot_token: your_token
chat_ids:
send_to_chat: true
send_to_telegram: true
log_join_and_leave_event: true
log_death_event: true
log_sleep_event: false
months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
messages:
  join: 'Player %playername% joined the game!'
  leave: 'Player %playername% left the game!'
  death: 'Player %playername% died! %deathmessage%'
  sleep: 'Player %playername% is sleeping!'
  telegram: '[%playername%] %message%'
  chat: '§7[§bTelegram§7] §f[%playername%] %message%'
  time: 'Time is %time% %emoji%\nDate is %month% %day%, Year %year%'
  online: 'There are %count% players online\n%players%'
