bot_token: your_token # your bot token from @BotFather remember to disable privacy mode
chats: # your chat list, you can add multiple chats use '-' to separate them
  - id: # your chat id, you can get it from @ScanIDBot
    thread: null # your thread id (optional) if you want to send messages to a specific thread. /setthread on telegram chat can be used to set the thread automatically
send_to_chat: true
send_to_telegram: true
log_join_and_leave_event: true
log_death_event: true
log_sleep_event: false
months: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
media_types: ['an image', 'a video', 'a document', 'an audio', 'a voice', 'a sticker', 'a contact', 'a location', 'a poll', 'a media']
messages:
  join: 'Player %playername% joined the game!'
  leave: 'Player %playername% left the game!'
  death: 'Player %playername% died! %deathmessage%'
  sleep: 'Player %playername% is sleeping!'
  telegram: '[%playername%]: %message%'
  media: '§7[§bTelegram§7] §f[%user%] sent %type%%caption%'
  chat: '§7[§bTelegram§7] §f[%user%] %message%'
  reply: '- §breply to §7%user%: %message%§r -\n'
  time: 'Time is %time% %emoji%\nDate is %month% %day%, Year %year%'
  online: 'There are %count% players online%players%'
