name: TelegramBridge
version: '${version}'
main: org.altart.telegrambridge.TelegramBridge
api-version: '1.13'
authors: [alt-art]
description: Simple plugin that fowards minecraft messages to telegram and vice versa
website: altart.top

commands:
  tbreload:
    description: Reloads the TelegramBridge configuration
    usage: /tbreload
    permission: telegrambridge.commands.reload
  tbreply:
    description: Reply using message_id to a message in telegram chat
    usage: /tbreply <message_id> <message>
    permission: telegrambridge.commands.reply
    aliases: [tbr]
  tbmention:
    description: Mention a user in a telegram chat
    usage: /tbmention <username> <message>
    permission: telegrambridge.commands.mention
    aliases: [tbm]

permissions:
    telegrambridge.commands.reload:
        description: Allows the user to reload the TelegramBridge configuration
        default: op
    telegrambridge.commands.reply:
        description: Allows the user to reply to a message in telegram chat
        default: true
    telegrambridge.commands.mention:
        description: Allows the user to mention a user in a telegram chat
        default: true
    telegrambridge.send:
        description: Allows the user to send messages to telegram chat
        default: true
    telegrambridge.receive:
        description: Allows the user to receive messages from telegram chat
        default: true
