name: TelegramBridge
version: '${version}'
main: org.altart.telegrambridge.TelegramBridge
api-version: '1.18'
authors: [alt-art]
description: Simple plugin that fowards minecraft messages to telegram and vice versa
website: altart.top

commands:
  tbreload:
    description: Reloads the TelegramBridge configuration
    usage: /tbreload
    permission: telegrambridge.commands.reload
  tbreply:
    description: Reply using message_id to a message in telegram chat
    usage: /tbreply <message_id> <message>
    permission: telegrambridge.commands.reply
    aliases: [tbr]
  tbmention:
    description: Mention a user in a telegram chat
    usage: /tbmention <username> <message>
    permission: telegrambridge.commands.mention
    aliases: [tbm]
