name: TelegramBridge
version: '${version}'
main: org.altart.telegrambridge.TelegramBridge
api-version: '1.18'
authors: [alt-art]
description: Simple plugin that fowards minecraft messages to telegram and vice versa
website: altart.top

commands:
  tbreload:
    description: Reloads the TelegramBridge configuration
    usage: /tgreload
    permission: telegrambridge.commands.reload
    aliases: [tbr]
