name: Release

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+*"]
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up JDK 8
          uses: actions/setup-java@v4
          with:
            java-version: '8'
            distribution: 'temurin'
        - name: Build with Gradle
          run: ./gradlew shadowJar
        - name: Release .jar
          run: |
            mv build/libs/TelegramBridge.jar TelegramBridge-${GITHUB_REF##*/}.jar
            ./.github/workflows/upload_asset.sh "alt-art/TelegramBridge" ./TelegramBridge-${GITHUB_REF##*/}.jar $GITHUB_TOKEN
