name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Set up JDK 17
          uses: actions/setup-java@v4
          with:
              java-version: '17'
              distribution: 'corretto'
        - name: Run tests
          run: ./gradlew test
        - name: Report test results
          uses: mikepenz/action-junit-report@v4
          if: success() || failure()
